### ISSUE TITLE
not able to post a tweet from flutter web

### ISSUE THREAD

**Issue by SanthoshMKunthe** [robertodoering/twitter_api#15]
i have used your api which is really wonderflull. . . however am not able to post using web app. . . have not checked android or ios. . . 

i am getting the following error. . .
 
```

Error: XMLHttpRequest error.
    dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 908:28                get current
packages/http/src/browser_client.dart 71:22                                       <fn>
dart-sdk/lib/async/zone.dart 1687:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 160:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 593:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1232:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37332:58                              <fn>



    at Object.createErrorWithStack (http://localhost:36121/dart_sdk.js:5074:12)
    at Object._rethrow (http://localhost:36121/dart_sdk.js:38925:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:36121/dart_sdk.js:38921:13)
    at Object._microtaskLoop (http://localhost:36121/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:36121/dart_sdk.js:38784:13)
    at http://localhost:36121/dart_sdk.js:34519:9

```

following usage creates above error. . . 
 ```
 twitterApi.tweetService
        .update(
      status: s,
    )
        .then((value) {
      print(value.toJson().toString());
    });
```

**Comment by robertodoering** [comment]
#12
